ruby "2.2.1"
source :rubygems
gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'json'
gem 'awesome_print'
gem 'google-api-client'
gem 'google_drive'
gem 'newrelic_rpm'
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'httparty'
